






(property (ptc :pt-counters-map p :peer top :topic)
	  :proofs? nil
          :TESTING-TIMEOUT 600
	  :hyps (^ (>= (params-meshMessageDeliveriesCap (car *factors2*))
		       (params-meshMessageDeliveriesThreshold (car *factors2*)))
                   (member-equal (cons p top) (strip-cars ptc))
                   (> (lookup-score p (calc-nbr-scores-map ptc *factors2* nil)) 0))
          (> (calcScoreTopic (lookup-counters p top ptc)
                                (lookup-weights
                                 (cdr *factors2*) top)
                                (car *factors2*))
             0))



;; scoring function attack
(property (ptc :pt-counters-map p :peer top :topic f :factors)
	  :proofs? nil
          :TESTING-TIMEOUT 600
	  :hyps (^ (>= (params-meshMessageDeliveriesCap (car f))
		       (params-meshMessageDeliveriesThreshold (car f)))
                   (member-equal (cons p top) (strip-cars ptc))
                   (> (lookup-score p (calc-nbr-scores-map ptc f nil)) 0))
          (> (calcScoreTopic (lookup-counters p top ptc)
                                (lookup-weights
                                 (cdr f) top)
                                (car f))
             0))

(let 
((F '(((:0TAG . PARAMS)
       (:ACTIVATIONWINDOW . 2)
       (:D . 0)
       (:DHIGH . 0)
       (:DLAZY . 0)
       (:DLOW . 0)
       (:FANOUTTTL . 1)
       (:GRAYLISTTHRESHOLD . 0)
       (:HBMINTERVAL . 1)
       (:MCACHEGSP . 0)
       (:MCACHELEN . 1)
       (:MESHMESSAGEDELIVERIESCAP . 0)
       (:MESHMESSAGEDELIVERIESTHRESHOLD . 0)
       (:MESHTIMEQUANTUM . 1)
       (:OPPORTUNISTICGRAFTTHRESHOLD . 0)
       (:P2CAP . 1)
       (:SEENTTL . 1)
       (:TIMEQUANTAINMESHCAP . 1)
       (:TOPICCAP . 1))
      (SE 1 1 -1 -1 -1 1 -1 -1)))
 (TOP 'SEC)
 (P 'P6)
 (PTC '(((P5 . FM)
         (:0TAG . COUNTERS)
         (:BADBEHAVIOUR . 0)
         (:FIRSTMESSAGEDELIVERIES . 74)
         (:INVALIDMESSAGEDELIVERIES . 0)
         (:MESHFAILUREPENALTY . 0)
         (:MESHMESSAGEDELIVERIES . 80)
         (:MESHTIME . 77))
        ((P6 . FM)
         (:0TAG . COUNTERS)
         (:BADBEHAVIOUR . 80)
         (:FIRSTMESSAGEDELIVERIES . 6)
         (:INVALIDMESSAGEDELIVERIES . 83)
         (:MESHFAILUREPENALTY . 68)
         (:MESHMESSAGEDELIVERIES . 7)
         (:MESHTIME . 1))
        ((P7 . FM)
         (:0TAG . COUNTERS)
         (:BADBEHAVIOUR . 0)
         (:FIRSTMESSAGEDELIVERIES . 68)
         (:INVALIDMESSAGEDELIVERIES . 0)
         (:MESHFAILUREPENALTY . 0)
         (:MESHMESSAGEDELIVERIES . 74)
         (:MESHTIME . 71))
        ((P5 . SE)
         (:0TAG . COUNTERS)
         (:BADBEHAVIOUR . 56)
         (:FIRSTMESSAGEDELIVERIES . 2)
         (:INVALIDMESSAGEDELIVERIES . 59)
         (:MESHFAILUREPENALTY . 94)
         (:MESHMESSAGEDELIVERIES . 3)
         (:MESHTIME . 8))
        ((P6 . SE)
         (:0TAG . COUNTERS)
         (:BADBEHAVIOUR . 0)
         (:FIRSTMESSAGEDELIVERIES . 94)
         (:INVALIDMESSAGEDELIVERIES . 0)
         (:MESHFAILUREPENALTY . 0)
         (:MESHMESSAGEDELIVERIES . 100)
         (:MESHTIME . 97))
        ((P7 . SE)
         (:0TAG . COUNTERS)
         (:BADBEHAVIOUR . 100)
         (:FIRSTMESSAGEDELIVERIES . 1)
         (:INVALIDMESSAGEDELIVERIES . 53)
         (:MESHFAILUREPENALTY . 88)
         (:MESHMESSAGEDELIVERIES . 2)
         (:MESHTIME . 7))
        ((P5 . SEC)
         (:0TAG . COUNTERS)
         (:BADBEHAVIOUR . 0)
         (:FIRSTMESSAGEDELIVERIES . 70)
         (:INVALIDMESSAGEDELIVERIES . 0)
         (:MESHFAILUREPENALTY . 0)
         (:MESHMESSAGEDELIVERIES . 76)
         (:MESHTIME . 73))
        ((P6 . SEC)
         (:0TAG . COUNTERS)
         (:BADBEHAVIOUR . 76)
         (:FIRSTMESSAGEDELIVERIES . 8)
         (:INVALIDMESSAGEDELIVERIES . 79)
         (:MESHFAILUREPENALTY . 64)
         (:MESHMESSAGEDELIVERIES . 9)
         (:MESHTIME . 3))
        ((P7 . SEC)
         (:0TAG . COUNTERS)
         (:BADBEHAVIOUR . 0)
         (:FIRSTMESSAGEDELIVERIES . 64)
         (:INVALIDMESSAGEDELIVERIES . 0)
         (:MESHFAILUREPENALTY . 0)
         (:MESHMESSAGEDELIVERIES . 70)
         (:MESHTIME . 67)))))
(calcScoreTopic (lookup-counters p top ptc)
                                (lookup-weights
                                 (cdr f) top)
                                (car f)))
